<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kelurahan as ModelsKelurahan;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dataKelurahan = [
            ["nama_kelurahan"=>"Bangunasri", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Banjarejo", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Blaran", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Bogorejo", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Jonggrang", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Karangsono", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Klagen", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Mangge", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Manjung", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Ngumpul", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Panggung", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Purwodadi", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Rejomulyo", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Tebon", "kecamatan_id"=>1],
            ["nama_kelurahan"=>"Belotan", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Bendo", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Bulak", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Bulugledeg", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Carikan", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Dukuh", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Duwet", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Kinandang", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Kleco", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Kledokan", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Lemahbang", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Pingkuk", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Setren", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Soco", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Tanjung", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Tegalarum", "kecamatan_id"=>2],
            ["nama_kelurahan"=>"Baluk", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Gebyog", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Gondang", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Grabahan", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Karangrejo", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Kauman", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Manisrejo", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Mantren", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Maron", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Patihan", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Pelem", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Prampelan", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Sambirembe", "kecamatan_id"=>3],
            ["nama_kelurahan"=>"Botok", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Geplak", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Ginuk", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Jungke", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Karas", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Kuwon", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Sobontoro", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Sumursongo", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Taji", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Temboro", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Temenggungan", "kecamatan_id"=>4],
            ["nama_kelurahan"=>"Bayem Taman", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Bayem Wetan", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Gunungan", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Jajar", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Jeruk", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Karangmojo", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Kartoharjo (Kertoharjo)", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Klurahan", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Mrahu", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Ngelang", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Pencol", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Sukowidi", "kecamatan_id"=>5],
            ["nama_kelurahan"=>"Balerejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Bogem", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Garon", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Genengan", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Giripurno", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Jambangan", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Karangrejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Kawedanan", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Mangunrejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Mojorejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Ngadirejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Ngentep", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Ngunut", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Pojok", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Rejosari", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Sampung", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Selorejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Sugihrejo", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Tladan", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Tulung", "kecamatan_id"=>6],
            ["nama_kelurahan"=>"Dukuh", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Kediren", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Kedungpanji", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Krowe", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Lembeyan Kulon", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Lembeyan Wetan", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Nguri", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Pupus", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Tapen", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Tunggur", "kecamatan_id"=>7],
            ["nama_kelurahan"=>"Baron", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Bulukerto", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Candirejo", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Kebonagung", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Kepolorejo", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Magetan", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Mangkujayan", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Purwosari", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Ringinagung", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Selosari", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Sukowinangun", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Tambakrejo", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Tambran", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Tawanganom", "kecamatan_id"=>8],
            ["nama_kelurahan"=>"Gulun", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Klagen Gambiran", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Kraton", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Malang", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Maospati", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Mranggen", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Ngujung", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Pandeyan", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Pesu", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Ronowijayan", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Sempol", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Sugihwaras", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Sumberejo", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Suratmajan", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Tanjungsepreh", "kecamatan_id"=>9],
            ["nama_kelurahan"=>"Baleasri", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Balegondo", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Bangsri", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Banjarejo", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Banjarpanjang", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Banyudono", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Mojopurno", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Ngariboyo", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Pendem", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Selopanggung", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Selotinatah", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Sumberdukun", "kecamatan_id"=>10],
            ["nama_kelurahan"=>"Driyorejo", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Gorang Gareng", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Kenongomulyo", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Nguntoronadi", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Petungrejo", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Purworejo", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Semen", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Simbatan", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Sukowidi", "kecamatan_id"=>11],
            ["nama_kelurahan"=>"Banjarejo", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Bedagung", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Cepoko", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Jabung", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Manjung", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Milangasri", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Ngiliran", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Panekan", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Rejomulyo", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Sidowayah", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Sukowidi", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Sumberdodol", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Tanjungsari", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Tapak", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Terung", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Turi", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Wates", "kecamatan_id"=>12],
            ["nama_kelurahan"=>"Bungkuk", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Joketro", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Krajan", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Mategal", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Ngaglik", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Nglopang", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Ngunut", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Parang", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Pragak", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Sayutan", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Sundul", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Tamanarum", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Trosono", "kecamatan_id"=>13],
            ["nama_kelurahan"=>"Bogoarum", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Bulugunung", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Buluharjo", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Dadi", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Ngancar", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Nitikan", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Pacalan", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Plaosan", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Plumpung", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Puntukdoro", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Randugede", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Sarangan", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Sendangagung", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Sidomukti", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Sumberagung", "kecamatan_id"=>14],
            ["nama_kelurahan"=>"Alastuwo", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Cileng", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Genilangit", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Gonggang", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Janggan", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Plangkrongan", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Poncol", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Sombo", "kecamatan_id"=>15],
            ["nama_kelurahan"=>"Campursari", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Durenan", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Getasanyar", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Kalang", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Sambirobyong", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Sidokerto", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Sidomulyo", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Sidorejo", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Sumbersawit", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Widorokandang", "kecamatan_id"=>16],
            ["nama_kelurahan"=>"Bandar", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Bibis", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Bogem", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Bulu", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Kalangketi", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Kedungguwo", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Kembangan", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Kentangan", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Pojoksari", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Sukomoro", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Tamanan", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Tambakmas", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Tinap", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Truneng", "kecamatan_id"=>17],
            ["nama_kelurahan"=>"Duyung", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Jomblang", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Kepuhrejo", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Kerang", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Kerik", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Kiringan", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Kuwonharjo", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Madigondo", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Sawojajar", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Takeran", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Tawangrejo", "kecamatan_id"=>18],
            ["nama_kelurahan"=>"Waduk", "kecamatan_id"=>18]
        ];

        foreach ($dataKelurahan as $kelurahan) {
            ModelsKelurahan::create($kelurahan);
        }
    }
}
